### ISSUE TITLE
"fatal: reference is not a tree" when cloning with submodules

### ISSUE THREAD

**Issue by sneakernets** [jpcima/ADLplug#2]
I'm trying to clone this and I can't get off the ground due to the submodules not being in sync with the project. I've only seen errors like this once or twice in my life and it's usually due to something in the submodule commits not being pushed.

**Comment by jpcima** [comment]
Good catch. I have screwed up here, by making personal commits in the JUCE submodule.
I have added to JUCE some fixes which have since been accepted in their develop branch, and in top of that I have added the LV2 support commits which they don't yet have as an upstream feature.

For now, I give you an archive of current source of JUCE which I have. [JUCE.tar.gz](https://github.com/jpcima/ADLplug/files/1995884/JUCE.tar.gz)

Please note that ADLplug is not yet very useful software. While it is able to play, it cannot yet load instruments or do dynamic control, just the default bank will play.
I have put the development on hold until dynamic edition of instruments becomes possible, which @Wohlstand has self-assigned. I should checkout with him about status of this, and possibly continue this work myself.

In this project, I prefer not to introduce crap workarounds I am going to rework later on.
While this is on hold, I have prefered to enhance adljack instead for more dynamic control features.

**Comment by sneakernets** [comment]
Alright - a friend of mine wanted to use my patches in her music project and I've been trying to find a solution with what is available right now. The only issue is that she has a deadline and I'm not sure if I can come up with something in time. Would adljack be a solution?

**Comment by jpcima** [comment]
If you want the most basic support of banks, I may be able to come up with a super shitty 10 minute solution potentially. I would isolate this one in a separate branch.

What os do you want this made for?
ADLjack has support for MIDI virtual port, including on Windows. But if you will want to reroute the audio output, I'm not sure at all there will be a solution to do that.

**Comment by sneakernets** [comment]
oh! Mac OS 10.12 is what my friend uses, and her DAW only accepts VST2 (so no AU or VST3). I happen to use Mac OS as well so I can use this too.

**Comment by jpcima** [comment]
alright let's do it

**Comment by jpcima** [comment]
Having a lot of trouble pushing to github right now. Dunno what is going on.

**Try this:**
[ADLplug-mac+bankloader.tar.gz](https://github.com/jpcima/ADLplug/files/1996441/ADLplug-mac.bankloader.tar.gz)

I have never tested mac, I'm not even sure the directory structure of the VST bundle is completely right. But, you're going to tell me this.

If I got this right, loading banks must now be possible.

**Comment by sneakernets** [comment]
I just gave her that file and I will let you know. I'm currently at work on a Windows machine so I can't test it myself (boo)

**Comment by sneakernets** [comment]
Alright it works, but there doesn't seem to be a way to change the instrument from the VST itself. No  host-automatable parameters that we can see, so I assume it's listening for MIDI program changes? I know that sounds obvious but Propellerhead Reason is one of the most frustrating DAWs to use when it comes to stuff like VSTs,

**Comment by sneakernets** [comment]
And let me clarify... by instrument I mean the instrument number changes (from Trumpet to Trumbone for example) and not the FM parameters.

**Comment by jpcima** [comment]
Parameters are not done, and none of the sliders or knobs are going to change a thing.
It will respond to program and bank changes by midi, because libADLMIDI supports that by itself. But from the UI, there is no way to do that right now.
The UI controls which respond are ones which are not linked to parameters: the chip count, and emulator.

**Comment by sneakernets** [comment]
Aaah okay thank you. I figured that was the case. Still it's amazing a $400 DAW can't send midi commands to VSTi other than the simple note events that even a keyboard from the 80s can do.

**Comment by jpcima** [comment]
It's fixed, now ADLplug has all the parts needed to build available from the repository.
I close this issue.
